---
title: "Visualization 3"
output: html_document
---

### Goal vs Pledged Amounts

Now, let’s dive deeper! The plot below displays a sample of 30,000 successful and failed projects, comparing their goal amounts with the actual pledged amounts. Both axes are on a logarithmic scale, and a 45-degree red line separates successful projects (above the line) from failed ones (below the line). As with our previous visualization, this is created with Plotly, so you can hover over individual points to see details about specific projects—or click on the dots to visit the project pages directly!

```{r, message = FALSE, warning = FALSE, tidy = 'styler'}
library(plotly)

set.seed(123)

kickstarter.filtered <- kickstarter[kickstarter$State %in% c("Successful", "Failed"), ]
kickstarter.filtered.sampled <- kickstarter[sample(nrow(kickstarter.filtered), 100000), ]
kickstarter.filtered.sampled.slim <- subset(kickstarter.filtered.sampled, select = -c(Country, Launched, Deadline))

fig <- plot_ly(data = kickstarter.filtered.sampled.slim, x = ~Goal, y = ~Pledged,
        type = "scatter", mode = "markers",
        marker = list(color = "rgba(0, 0, 0, 0.1)", size = 6),
        text = ~paste(
          "Name:", Name,
          "<br>Category:", Category,
          "<br>Subcategory:", Subcategory,
          "<br>State:", State,
          "<br>Backers:", format(Backers, big.mark="'", trim = TRUE),
          "<br>Goal Amount:", format(Goal, big.mark="'", trim = TRUE),
          "<br>Pledged Amount:", format(Pledged, big.mark="'", trim = TRUE)
        ),
        hoverinfo = "text",
        customdata = ~ID) %>%
  layout(
    title = "Goal vs Pledged Amounts",
    xaxis = list(title = "Goal Amount (Log Scale)", type = "log"),
    yaxis = list(title = "Pledged Amount (Log Scale)", type = "log"),
    width = 800,
    margin = list(t = 60, b = 60),
    shapes = list(
      type = "line",
      x0 = 1,
      x1 = max(kickstarter.filtered.sampled.slim$Pledged),
      y0 = 1,
      y1 = max(kickstarter.filtered.sampled.slim$Pledged),
      line = list(dash="dash", width=2, color = "red"),
      layer = "below"
    )
  )

fig <-  fig %>% toWebGL()

fig
```

<script>
// Add a listener for plotly click events
document.addEventListener('DOMContentLoaded', function() {
  const plot = document.getElementsByClassName('plotly')[2];
  if (plot) {
    plot.on('plotly_click', function(data) {
      // Get the customdata (URL) for the clicked point
      const id = data.points[0].customdata;
      if (id) {
        // Open the URL in a new browser tab
        window.open("https://www.kickstarter.com/projects/"+id+"/"+id, '_blank');
      }
    });
  }
});
</script>

We applied transparency to the dots, making it easy to see that the majority of projects have goal amounts between $100 and $100k. If you zoom in, you'll notice that there are almost no projects directly below the red line. This suggests that once a project comes close to reaching its goal amount, it is very likely to succeed.

The outlier projects are also quite interesting. Those clustered near the X-axis represent ambitious projects with lofty goals but disappointing support. Conversely, the ones near the Y-axis showcase modest projects with humble $1 goals that ended up wildly surpassing their expectations.
